apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.metadata.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $val := .Values.backend.image.selectorLabels }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.backend.image.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.backend.containerName }}
          image: "{{ .Values.backend.image.repository }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: backend
              containerPort: 5000
          resources:
            limits:
              cpu: 256m
            requests:
              cpu: 128m
          livenessProbe:
            httpGet:
              path: /
              port: backend
            failureThreshold: 1
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: backend
            initialDelaySeconds: 5
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /
              port: backend
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 11000
            capabilities:
              drop:
                - NET_RAW
                - ALL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.metadata.name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $val := .Values.frontend.image.selectorLabels }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.frontend.image.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.frontend.containerName }}
          image: "{{ .Values.frontend.image.repository }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: frontend
              containerPort: 4000
          resources:
            limits:
              cpu: 256m
            requests:
              cpu: 128m
          livenessProbe:
            httpGet:
              path: /
              port: frontend
            failureThreshold: 1
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: frontend
            initialDelaySeconds: 5
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /
              port: frontend
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 11000
            capabilities:
              drop:
                - NET_RAW
                - ALL
          envFrom:
            - configMapRef:
                name: frontend-configmap
